// src/components/add-employee/AddEmployee.tsx
import Input from "@components/Input/Input";
import useAddEmployee from "@hooks/useAddEmployee";

const AddEmployee = ({closeAddModal}: {closeAddModal: () => void}) => {
  const { register, handleSubmit, errors, submitForm } = useAddEmployee({closeAddModal})
  return (
    <div className="add-employee-modal fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 min-h-screen">
      <div className="bg-white rounded-2xl shadow-xl max-w-md w-full">
        <div className="modal_header flex justify-between items-center mb-4 border-b border-gray-300 p-5">
          <h2 className="text-xl font-semibold">Add Employee</h2>
          <button onClick={() => closeAddModal()} className="text-gray-500 text-3xl hover:text-gray-700">
            &times;
          </button>
        </div>
        <form className="modal_body p-5" onSubmit={handleSubmit(submitForm)} >
          <Input label="Name" error={errors.empName?.message as string} name="empName" register={register} />
          <Input label="Email" type="email" error={errors.empEmail?.message as string} name="empEmail" register={register} />
          <div className="mb-4">
            <label htmlFor="address" className="block font-semibold mb-1">Address</label>
            <textarea id="address" {...register("empAddress")} className="w-full p-2 outline-none border border-gray-300 rounded-md"></textarea>
            <p className='text-red-500 mt-1 lowercase' > {errors.empAddress?.message} </p>
          </div>
          <Input label="Phone" type="tel" error={errors.empPhone?.message as string} name="empPhone" register={register} />
          <div className="modal_footer p-5 flex gap-4 justify-end bg-gray-200">
            <button onClick={() => closeAddModal()} type="button">Cancel</button>
            <button type="submit" className="py-2 px-4 bg-[#218838] text-white rounded-md">Add</button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default AddEmployee;

// src/app/components/add-employee/add-employee.component.ts
import { Component, EventEmitter, inject, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { EmployeesService } from '../../services/employees.service';

@Component({
  selector: 'app-add-employee',
  imports: [ReactiveFormsModule],
  templateUrl: './add-employee.component.html',
  styleUrl: './add-employee.component.css'
})
export class AddEmployeeComponent implements OnInit {
  @Output() closeModal = new EventEmitter();
  @Output() addSuccess = new EventEmitter();
  addEmployeeForm!: FormGroup;
  private readonly formBuilder = inject(FormBuilder);
  private readonly employeesService = inject(EmployeesService);
  ngOnInit(): void {
    this.addEmployeeForm = this.formBuilder.group({
      empName: [null, [Validators.required]],
      empEmail: [null, [Validators.required, Validators.email]],
      empAddress: [null, [Validators.required]],
      empPhone: [null, [Validators.required, Validators.pattern(/^01[0125][0-9]{8}$/)]]
    })
  }
  submitForm() {
    if (this.addEmployeeForm.valid) {
      this.employeesService.addEmployee(this.addEmployeeForm.value).subscribe({
        next: (res) => {
          if (res === 1) {
            this.addEmployeeForm.reset();
            this.addSuccess.emit(); // to update all data after add
            this.closeModal.emit();
          }
        },
        error: (err) => {
          console.log(err);
        }
      })
    } else {
      this.addEmployeeForm.markAllAsTouched()
    }
  }
  closeAddEmployeeModal() {
    this.closeModal.emit();
  }
}

<div class="add-employee-modal fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 min-h-screen">
  <div class="bg-white rounded-2xl shadow-xl max-w-md w-full">
    <div class="modal_header flex justify-between items-center mb-4 border-b border-gray-300 p-5">
      <h2 class="text-xl font-semibold">Add Employee</h2>
      <button (click)="closeAddEmployeeModal()" class="text-gray-500 text-3xl hover:text-gray-700">
        &times;
      </button>
    </div>
    <form class="modal_body p-5" [formGroup]="addEmployeeForm" (ngSubmit)="submitForm()">
      <div class="mb-4">
        <label for="name" class="block font-semibold mb-1">Name</label>
        <input type="text" id="name" formControlName="empName" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (addEmployeeForm.get('empName')?.errors && addEmployeeForm.get('empName')?.touched) {
          <p class="text-sm text-red-500 mt-1">* Name is required</p>
        }
      </div>
      <div class="mb-4">
        <label for="email" class="block font-semibold mb-1">Email</label>
        <input type="email" id="email" formControlName="empEmail" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (addEmployeeForm.get('empEmail')?.errors && addEmployeeForm.get('empEmail')?.touched) {
          @if (addEmployeeForm.get('empEmail')?.getError('required')) {
            <p class="text-sm text-red-500 mt-1">* Email is required</p>
          } @else if (addEmployeeForm.get('empEmail')?.getError('email')) {
            <p class="text-sm text-red-500 mt-1">* Enter valid Email</p>
          }
        }
      </div>
      <div class="mb-4">
        <label for="address" class="block font-semibold mb-1">Address</label>
        <textarea id="address" formControlName="empAddress" class="w-full p-2 outline-none border border-gray-300 rounded-md"></textarea>
        @if (addEmployeeForm.get('empAddress')?.errors && addEmployeeForm.get('empAddress')?.touched) {
          <p class="text-sm text-red-500 mt-1">* Address is required</p>
        }
      </div>
      <div class="mb-4">
        <label for="phone" class="block font-semibold mb-1">Phone</label>
        <input type="tel" id="phone" formControlName="empPhone" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (addEmployeeForm.get('empPhone')?.errors && addEmployeeForm.get('empPhone')?.touched) {
          @if (addEmployeeForm.get('empPhone')?.getError('required')) {
            <p class="text-sm text-red-500 mt-1">* Phone is required</p>
          } @else if (addEmployeeForm.get('empPhone')?.getError('pattern')) {
            <p class="text-sm text-red-500 mt-1">* Phone should be 11 number only and should begin with 011, 012 or 010</p>
          }
        }
      </div>
      <div class="modal_footer p-5 flex gap-4 justify-end bg-gray-200">
        <button type="button" (click)="closeAddEmployeeModal()">Cancel</button>
        <button [disabled]="addEmployeeForm.invalid" type="submit" class="py-2 px-4 bg-[#218838] text-white rounded-md">Add</button>
      </div>
    </form>
  </div>
</div>
