// src/components/edit-employee/EditEmployee.tsx
import Input from "@components/Input/Input";
import useEditEmployee from "@hooks/useEditEmployee";
import type { IEmployee } from "@interfaces/iemployee";

type EmployeeProps = {
  closeEditModal: () => void,
  employee: IEmployee
}

const EditEmployee = ({closeEditModal, employee}: EmployeeProps) => {
  const { register, handleSubmit, errors, submitForm } = useEditEmployee({ closeEditModal, employee })
  return (
    <div className="add-employee-modal fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-2xl shadow-xl max-w-md w-full">
        <div className="modal_header flex justify-between items-center mb-4 border-b border-gray-300 p-5">
          <h2 className="text-xl font-semibold">Edit Employee</h2>
          <button onClick={() => closeEditModal()} className="text-gray-500 text-3xl hover:text-gray-700">
            &times;
          </button>
        </div>
        <form className="modal_body p-5" onSubmit={handleSubmit(submitForm)} >
          <Input label="Name" error={errors.empName?.message as string} name="empName" register={register} />
          <Input label="Email" type="email" error={errors.empEmail?.message as string} name="empEmail" register={register} />
          <div className="mb-4">
            <label htmlFor="address" className="block font-semibold mb-1">Address</label>
            <textarea id="address" {...register("empAddress")}  className="w-full p-2 outline-none border border-gray-300 rounded-md"></textarea>
            <p className='text-red-500 mt-1 lowercase' > {errors.empAddress?.message} </p>
          </div>
          <Input label="Phone" type="tel" error={errors.empPhone?.message as string} name="empPhone" register={register} />
          <div className="modal_footer p-5 flex gap-4 justify-end bg-gray-200">
            <button onClick={() => closeEditModal()} type="button" >Cancel</button>
            <button type="submit" className="py-2 px-4 bg-[#218838] text-white rounded-md">Save</button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default EditEmployee;

// src/app/components/edit-employee/edit-employee.component.ts
import { Component, EventEmitter, inject, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { EmployeesService } from '../../services/employees.service';

@Component({
  selector: 'app-edit-employee',
  imports: [ReactiveFormsModule],
  templateUrl: './edit-employee.component.html',
  styleUrl: './edit-employee.component.css'
})
export class EditEmployeeComponent implements OnInit {
  @Output() closeEditModal = new EventEmitter();
  @Output() editSuccess = new EventEmitter();
  @Input() empId!: number;
  editEmployeeForm!: FormGroup;
  private readonly formBuilder = inject(FormBuilder);
  private readonly employeesService = inject(EmployeesService);
  ngOnInit(): void {
    this.editEmployeeForm = this.formBuilder.group({
      empId: [null],
      empName: [null, [Validators.required]],
      empEmail: [null, [Validators.required, Validators.email]],
      empAddress: [null, [Validators.required]],
      empPhone: [null, [Validators.required, Validators.pattern(/^01[0125][0-9]{8}$/)]]
    })
    this.getEmployee();
  }
  submitForm() {
    if (this.editEmployeeForm.valid) {
      this.employeesService.editEmployee(this.editEmployeeForm.value).subscribe({
        next: (res) => {
          if (res === 1) {
            this.editEmployeeForm.reset();
            this.editSuccess.emit(); // to update all data after edit
            this.closeEditModal.emit();
          }
        },
        error: (err) => {
          console.log(err);
        }
      })
    } else {
      this.editEmployeeForm.markAllAsTouched();
    }
  }
  getEmployee() {
    this.employeesService.getEmployee(this.empId).subscribe({
      next: (res) => {
        this.fillForm(res);
      },
      error: (err) => {
        console.log(err);
      }
    })
  }
  fillForm(formData: any) {
    this.editEmployeeForm.setValue({
      empId: formData.empId,
      empName: formData.empName,
      empEmail: formData.empEmail,
      empAddress: formData.empAddress,
      empPhone: formData.empPhone
    })
  }
  closeEditEmployeeModal() {
    this.closeEditModal.emit();
  }
}

<div class="add-employee-modal fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
  <div class="bg-white rounded-2xl shadow-xl max-w-md w-full">
    <div class="modal_header flex justify-between items-center mb-4 border-b border-gray-300 p-5">
      <h2 class="text-xl font-semibold">Edit Employee</h2>
      <button (click)="closeEditEmployeeModal()" class="text-gray-500 text-3xl hover:text-gray-700">
        &times;
      </button>
    </div>
    <form class="modal_body p-5" [formGroup]="editEmployeeForm" (ngSubmit)="submitForm()" >
      <div class="mb-4">
        <label for="name" class="block font-semibold mb-1">Name</label>
        <input type="text" id="name" formControlName="empName" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (editEmployeeForm.get('empName')?.errors && editEmployeeForm.get('empName')?.touched) {
          <p class="text-sm text-red-500 mt-1">* Name is required</p>
        }
      </div>
      <div class="mb-4">
        <label for="email" class="block font-semibold mb-1">Email</label>
        <input type="email" id="email" formControlName="empEmail" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (editEmployeeForm.get('empEmail')?.errors && editEmployeeForm.get('empEmail')?.touched) {
          @if (editEmployeeForm.get('empEmail')?.getError('required')) {
            <p class="text-sm text-red-500 mt-1">* Email is required</p>
          } @else if (editEmployeeForm.get('empEmail')?.getError('email')) {
            <p class="text-sm text-red-500 mt-1">* Enter valid Email</p>
          }
        }
      </div>
      <div class="mb-4">
        <label for="address" class="block font-semibold mb-1">Address</label>
        <textarea id="address" formControlName="empAddress" class="w-full p-2 outline-none border border-gray-300 rounded-md"></textarea>
        @if (editEmployeeForm.get('empAddress')?.errors && editEmployeeForm.get('empAddress')?.touched) {
          <p class="text-sm text-red-500 mt-1">* Address is required</p>
        }
      </div>
      <div class="mb-4">
        <label for="phone" class="block font-semibold mb-1">Phone</label>
        <input type="tel" id="phone" formControlName="empPhone" class="w-full p-2 outline-none border border-gray-300 rounded-md" />
        @if (editEmployeeForm.get('empPhone')?.errors && editEmployeeForm.get('empPhone')?.touched) {
          @if (editEmployeeForm.get('empPhone')?.getError('required')) {
            <p class="text-sm text-red-500 mt-1">* Phone is required</p>
          } @else if (editEmployeeForm.get('empPhone')?.getError('pattern')) {
            <p class="text-sm text-red-500 mt-1">* Phone should be 11 number only and should begin with 011, 012 or 010</p>
          }
        }
      </div>
      <div class="modal_footer p-5 flex gap-4 justify-end bg-gray-200">
        <button type="button" (click)="closeEditEmployeeModal()">Cancel</button>
        <button type="submit" class="py-2 px-4 bg-[#218838] text-white rounded-md">Save</button>
      </div>
    </form>
  </div>
</div>
